# Generated by Django 4.0.4 on 2022-05-03 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_author_last_name_alter_author_bio'),
        ('blog_posts', '0003_alter_blogpost_created_on_alter_blogpost_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_name', to='authors.author'),
        ),
    ]
