# Generated by Django 4.0.4 on 2022-05-03 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_alter_author_first_name_alter_author_last_name'),
        ('blog_posts', '0004_alter_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_name', to='authors.author'),
        ),
    ]
