# Generated by Django 4.0.4 on 2022-05-03 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='Lives off their writing'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='author_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
