# Generated by Django 4.0.4 on 2022-05-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_author_bio_alter_author_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='artist bio'),
        ),
    ]
