# Generated by Django 4.0.4 on 2022-05-03 13:25

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '0005_alter_author_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.PROTECT, related_name='author_lastname', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='artist bio', max_length=250),
        ),
    ]
