# Generated by Django 4.0.4 on 2022-05-03 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '0006_author_last_name_alter_author_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.ForeignKey(default='User1', on_delete=django.db.models.deletion.PROTECT, related_name='author_lastname', to=settings.AUTH_USER_MODEL),
        ),
    ]
